#!/bin/bash

# Replace the strings CONJUR_AUTHN_LOGIN and CONJUR_AUTHN_API_KEY into the forwarder config

login=$IDENTITY_ENV_CONJUR_AUTHN_LOGIN
api_key=$IDENTITY_ENV_CONJUR_AUTHN_API_KEY

if [ -z "$login" ]; then 
  echo "Missing CONJUR_AUTHN_LOGIN from linked 'identity' container"
  exit 1; 
fi

if [ -z "$api_key" ]; then 
  echo "Missing CONJUR_AUTHN_API_KEY from linked 'identity' container"
  exit 1; 
fi

# http://stackoverflow.com/a/10660730
urlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo "${encoded}"    # You can either set a return variable (FASTER) 
  REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
}

cd /opt/openresty/nginx/conf/
login_encoded=$(urlencode "$login")
cat forward.conf.template | sed s/@CONJUR_AUTHN_LOGIN@/$login_encoded/ | sed s/@CONJUR_AUTHN_API_KEY@/$api_key/ > forward.conf

cd -

nginx -g "daemon off; error_log /dev/stderr info;"
