#!/bin/bash

# Replace the strings CONJUR_AUTHN_LOGIN and CONJUR_AUTHN_API_KEY into the forwarder config

login=$IDENTITY_ENV_CONJUR_AUTHN_LOGIN
api_key=$IDENTITY_ENV_CONJUR_AUTHN_API_KEY

if [ -z "$login" ]; then 
  echo "Missing CONJUR_AUTHN_LOGIN from linked 'identity' container"
  exit 1; 
fi

if [ -z "$api_key" ]; then 
  echo "Missing CONJUR_AUTHN_API_KEY from linked 'identity' container"
  exit 1; 
fi

function urlencode() {
    local data
    if [[ $# != 1 ]]; then
        echo "Usage: $0 string-to-urlencode"
        return 1
    fi
    data="$(curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "$1" "")"
    if [[ $? != 3 ]]; then
        echo "Unexpected error" 1>&2
        return 2
    fi
    echo "${data##/?}"
    return 0
}

login=$(urlencode $login)

cd /opt/openresty/nginx/conf/

cat forward.conf.template | sed s/@CONJUR_AUTHN_LOGIN@/$login/ | sed s/@CONJUR_AUTHN_API_KEY@/$api_key/ > forward.conf

cd -

nginx -g "daemon off; error_log /dev/stderr info;"
