backend:
  build: backend
  external_links:
  - webapp_identity:identity
service:
  build: service
  links:
  - backend:backend
gatekeeper:
  build: gatekeeper
  links:
  - service:service
  ports:
   - "8080:80"
